apiVersion: v1
kind: Service
metadata:
  name: python-k8s-app-service
spec:
  type: NodePort
  selector:
    app: python-k8s-app
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
      nodePort: 32005